# Generated by Django 5.2 on 2025-05-10 13:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Found',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=25)),
                ('category', models.CharField(max_length=20)),
                ('item_desc', models.CharField(max_length=100)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('date', models.DateField()),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=25)),
                ('category', models.CharField(max_length=20)),
                ('item_desc', models.CharField(max_length=100)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('date', models.DateField()),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MatchedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_collected', models.BooleanField(default=False)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('collected_by', models.CharField(max_length=255)),
                ('found_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.found')),
                ('lost_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.lost')),
            ],
        ),
    ]
